# Copyright 2021 ETH Zurich and University of Bologna
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


before_script:
  - pwd

stages:
  - build
  - test

dejagnu:
  stage: build
  before_script:
    - git clone git@iis-git.ee.ethz.ch:gnu/riscv-dejagnu.git
  script:
    # we make a separate install dir for dejagnu to make the arficat easier to glob
    - echo "Creating install directory"
    - mkdir -p dejagnu
    - echo "Running configure"
    - cd riscv-dejagnu
    -  ./configure --prefix=$(pwd)/../dejagnu
    - echo "Compiling"
    - make -j 32
    - echo "Installing"
    - make install
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - dejagnu/*
      - riscv-dejagnu/contrib/sum2junit.sh

gdb_sim:
  stage: build
  before_script:
  script:
    - echo "Creating install and build directory"
    - mkdir -p toolchain
    - mkdir -p build-gdb
    - echo "Running configure"
    - cd build-gdb
    - ../configure --target=riscv32-unknown-elf --prefix=$(pwd)/../toolchain --disable-werror --with-expat=yes --enable-gdb --disable-gas --disable-binutils --disable-ld --disable-gold --disable-gprof
    - echo "Compiling"
    - make -j 32
    - echo "Installing"
    - make install
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - toolchain/*
      # required to run tests
      - build-gdb/*


make_check:
  stage: test
  script:
    - echo "Entering build director"
    - cd build-gdb
    - echo "Running tests"
    - make check-sim RUNTEST=$(pwd)/../dejagnu/bin/runtest
    - echo "Generating junit test results"
    - /usr/sepp/bin/pip3.4 install --user junit2html
    # the contrib script can only with file endings that are like .sum.*
    - cp sim/testsuite/sim.sum sim.sum.x
    # sum -> junit.xml
    - ./sum2junit.sh sim.sum.x
    # junit.xml -> html
    - /usr/sepp/bin/python3.4 -m junit2htmlreport sim.xml
    # format output for log
    - /usr/sepp/bin/python3.4 -m junit2htmlreport --summary-matrix sim.xml

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - toolchain/*
      - build-gdb/sim/testsuite/sim.sum
      - build-gdb/sim/testsuite/sim.log
      - "*.html"
    reports:
      junit: "*.xml"
